[package]
name = "webcam_demo"
version = "0.1.0"
authors = ["annrobot"]

[dependencies]
ws = "*"
rscam = "*"
x264-sys = "*"
uuid = { version = "0.4", features = ["v4"] }

#static http server
iron = "0.5"
mount = "0.3"
staticfile = "0.4"
router = "0.5"